[workspace]
resolver = "2"
members = [
    "ids",
    "derive",
    "transparent",
    "table_seq",
    "imctk",
    "logger",
    "util",
    "ir",
    "abc-sys",

    # comment to force multi-line layout
]

[profile.release]
debug = true

[profile.dev]
opt-level = 1
