[package]
name = "imctk-derive"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3.1.0"
proc-macro2 = "1.0.81"
quote = { version = "1.0.36" }
syn = { version = "2.0.60" }
