[package]
name = "imctk_codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
derive-syn-parse = "0.2.0"
proc-macro2 = "1.0.81"
quote = { version = "1.0.36" }
syn = { version = "2.0.60", features = ["extra-traits"] }

[lints]
workspace = true
