[package]
name = "stable_set"
version = "0.1.0"
edition = "2021"

publish = false

[lints]
workspace = true

[dependencies]
hashbrown = { version = "0.14.5", default-features = false, features = ["inline-more"] }

[dev-dependencies]
zwohash = "0.1.2"
